version: 2

before:
  hooks:
    - go mod tidy -diff
    - go mod download
    - go mod verify

builds:
  - main: ./...
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - arm64
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -s -w

gomod:
  proxy: true
  env:
    - GOPROXY=https://proxy.golang.org,direct
    - GOSUMDB=sum.golang.org
  mod: readonly

nfpms:
  - vendor: Typist Tech Limited
    maintainer: "Typist Tech Limited <opensource+{{ .ProjectName }}@typist.tech>"
    license: MIT
    formats:
      - apk
      - deb
    contents:
      - src: ./LICENSE
        dst: /usr/share/doc/{{ .ProjectName }}/copyright
        file_info:
          mode: 0644
      - src: ./README.md
        dst: /usr/share/doc/{{ .ProjectName }}/README.md
        file_info:
          mode: 0644
    mtime: "{{ .CommitDate }}"

archives:
  - formats: [tar.gz]
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

homebrew_casks:
  - name: wpry
    homepage: https://github.com/typisttech/wpry
    description: |-
      Parses WordPress plugin and theme headers.
    skip_upload: auto
    repository:
      owner: typisttech
      name: homebrew-tap
      branch: tastendruck/wpry
      token: "{{ .Env.GORELEASER_HOMEBREW_GITHUB_TOKEN }}"
      pull_request:
        base:
          branch: main

checksum:
  name_template: "checksums.txt"

changelog:
  disable: true

release:
  use_existing_draft: true

metadata:
  mod_timestamp: "{{ .CommitTimestamp }}"
