name: Dependabot Auto-merge

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    uses: typisttech/.github/.github/workflows/dependabot-auto-merge.yml@2273764b628c3b4b05116711ea206967f085a14b # v5.5.2
    with:
      minor: true
      patch: true
