name: Dependabot Auto-merge

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    uses: typisttech/.github/.github/workflows/dependabot-auto-merge.yml@63fe4f651bb4747b3b17be96c32fcffd5954882c # v5.3.0
    with:
      minor: true
      patch: true
