name: Lint

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  actions:
    uses: typisttech/.github/.github/workflows/lint-actions.yml@6187a0d63e5c2b66925803ffe9c4a0fa1994a243 # v5.0.0

  go:
    uses: typisttech/.github/.github/workflows/lint-go.yml@6187a0d63e5c2b66925803ffe9c4a0fa1994a243 # v5.0.0
    with:
      golangci-lint: true
      golangci-lint-version: v2.11 # Must be kept in sync with @../../mise.toml

  wait-for-all-lint:
    needs:
      - actions
      - go
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
