name: Lint

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  actions:
    uses: typisttech/.github/.github/workflows/lint-actions.yml@7b89b88a2e9768adc532a741ec37de5921ad248e # v5.1.1

  go:
    uses: typisttech/.github/.github/workflows/lint-go.yml@7b89b88a2e9768adc532a741ec37de5921ad248e # v5.1.1
    with:
      golangci-lint: true
      golangci-lint-version: v2.11 # Must be kept in sync with @../../mise.toml

  wait-for-all-lint:
    needs:
      - actions
      - go
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
