name: Release Drafter

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

permissions:
  contents: write
  pull-requests: read

jobs:
  release-drafter:
    uses: typisttech/.github/.github/workflows/release-drafter.yml@8c3b859e35165a6e81a660713be195ec61d2ca1d # v5.2.1
